# Generated by Django 4.2.13 on 2024-05-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorties', '0007_participation_sortieproposee_participation_sortie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sortie',
        ),
    ]
