# Generated by Django 4.2.13 on 2024-05-26 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sorties', '0008_delete_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='vient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('sortie', 'membre')},
        ),
    ]
