# Generated by Django 4.2.13 on 2024-05-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorties', '0009_alter_participation_vient_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
