# Generated by Django 4.2.13 on 2024-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorties', '0010_alter_participation_unique_together_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_profile_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
