# Generated by Django 4.2.13 on 2024-06-05 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sorties', '0011_profile_other_profile_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeamis',
            name='administrateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groupes_administres', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
