# Generated by Django 4.2.13 on 2024-06-05 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sorties', '0012_groupeamis_administrateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeamis',
            name='membres',
            field=models.ManyToManyField(related_name='groupes', to=settings.AUTH_USER_MODEL),
        ),
    ]
